services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    # networks:
    #   - backend
    # ports:
    #   - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost #keycloak
      KC_HOSTNAME_PORT: "8080"
      KC_HOSTNAME_STRICT: "false"
      KC_PROXY: edge
      # KC_HEALTH_ENABLED: "true"
      # KC_METRICS_ENABLED: "true"
      # KC_FEATURES: token-exchange
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: ["start-dev"]
  
  node:
    build: ./app
    environment:
      NODE_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SESSION_SECRET: your_session_secret
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app
    # networks:
    #   - frontend
    #   - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - node
      - keycloak
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    # networks:
    #   - frontend
    #   - backend

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    # networks:
    #   - backend
volumes:
  postgres-data:
  redis-data:
