services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
#    networks:
#      - app-network
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    depends_on:
      - postgres
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      # KC_DB_DATABASE: keycloak
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      #KC_HOSTNAME_ADMIN: http://localhost:8080
      # KC_LOG_LEVEL: DEBUG
      # KC_HOSTNAME: http://localhost:8080
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: "8080"
      KC_HOSTNAME_STRICT: "false"
      KC_PROXY: edge
      #KC_HOSTNAME_PORT: "8080"
      #KC_PROXY: edge
      #KC_HEALTH_ENABLED: true
      #KC_METRICS_ENABLED: true
    ports:
      - "8080:8080"
    command: ["start-dev"]
#    networks:
#      - app-network
    
volumes:
  postgres-data:

# networks:
#   app-network:
#     driver: bridge

#  app:
#    build:
#      context: ./app
#      dockerfile: Dockerfile
#    volumes:
#      - ./app:/usr/src/app
#      - /usr/src/app/node_modules
#    environment:
#      DB_HOST: postgres
#      DB_PORT: 5432
#      DB_USER: admin
#      DB_PASSWORD: admin
#      DB_NAME: ride_sharing
#      KEYCLOAK_URL: http://localhost:8080
#      KEYCLOAK_REALM: ride-sharing
#      KEYCLOAK_CLIENT_ID: ride-sharing-app
#    networks:
#      - app-network
#    ports:
#      - "3000:3000"
#    command: ["npx", "nodemon", "-L", "app.js"]
